### ISSUE TITLE
Investigate the lowest z-scores

### ISSUE THREAD

**Issue by whoopsedesy** [sasansom/sedes#41]
The distribution of *z*-scores has a small number of very low values. Investigate these to see if they arise from errors.

![z-dist all](https://user-images.githubusercontent.com/53617134/108257450-af78fc80-7156-11eb-8dde-fe46381971cd.png)

Here are the lowest 50:
```
                z x     work book_n line_n word_n          word        lemma sedes metrical_shape scanned num_scansions
233527 -14.662878 1    Dion.     20    236      5        λυαίου       λυαῖος  10.0            +++    auto             1
90951  -12.922848 1      Il.      5    593      4      κυδοιμὸν     κυδοιμός   4.5            -+-    auto             1
472197 -10.816654 1   Theoc.     22    179      4  ὑμεναιώσουσι     ὑμεναιόω   6.0         --+++-    auto             1
347746 -10.440307 1      Od.     11    419      4      τραπέζας      τράπεζα   6.5            -++    auto             1
107107 -10.000000 1      Il.      9    389      4      ἀφροδίτῃ     ἀφροδίτη   6.0           --++    auto             1
379474 -10.000000 1      Od.     20     73      2      ἀφροδίτη     ἀφροδίτη   2.0           --++    auto             1
165027  -9.848858 1      Il.     22     27      4        ὀπώρης        ὀπώρα   2.5            -++    auto             1
450325  -8.829666 1     Q.S.     13    517      6      ἀριστέας     ἀριστεύς   8.5           -+--    auto             1
152849  -8.803408 2      Il.     18    484      4       σελήνην       σελήνη   6.5            -++    auto             1
414589  -8.803408 2     Q.S.      5      8      6        σελήνη       σελήνη   6.5            -++    auto             1
377746  -8.774964 1      Od.     19    439      5         λόχμῃ        λόχμη   4.0             ++    auto             1
21483   -8.124038 1   Argon.      2    714      4        χορείῃ       χορεία   6.5            -++    auto             1
353425  -7.810250 1      Od.     13    123      6       ὁδιτάων       ὁδίτης   6.5           -+++    auto             1
396521  -7.698889 1     Q.S.      1    228      4      ἀντίθεον     ἀντίθεος   5.0           +--+    auto             1
397629  -7.615773 1     Q.S.      1    391      1        χάρμης        χάρμη   1.0             ++    auto             1
440757  -7.549834 2     Q.S.     11    214      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
482394  -7.549834 2   Theog.    Th.    864      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
304633  -7.211103 1    Dion.     48    451      5        πορείῃ       πορεία  10.0            +++    auto             1
414956  -7.141428 1     Q.S.      5     61      3        ἀπήνας        ἀπήνη   2.5            -++    auto             1
274279  -7.035624 1    Dion.     37    773      6          ἐνυώ         ἐνυώ  10.0            +++    auto             1
478348  -7.035624 1   Theog.    Th.    273      4          ἐνυώ         ἐνυώ   6.5            -++    auto             1
389184  -7.028344 1      Od.     23    106      3    προσφάσθαι     πρόσφημι   3.0            +++    auto             1
85775   -7.000000 1      Il.      4    412      2         σιωπῇ        σιωπή   2.5            -++    auto             1
61007   -6.939065 4 Hom.Hymn      4     89      3       προσέφη     πρόσφημι   4.0            --+    auto             1
61697   -6.939065 4 Hom.Hymn      4    189      3       προσέφη     πρόσφημι   4.0            --+    auto             1
143751  -6.939065 4      Il.     16    842      4       προσέφη     πρόσφημι   4.0            --+    auto             1
348789  -6.939065 4      Od.     11    565      4       προσέφη     πρόσφημι   4.0            --+    auto             1
44435   -6.855655 1   Argon.      4   1455      6       ἀολλεῖς       ἀολλής  10.5            -++    auto             1
72348   -6.633250 1      Il.      1    438      3     ἑκατόμβην     ἑκατόμβη   2.0           --++    auto             1
430848  -6.633250 1     Q.S.      8    322      1         λαιμῷ       λαιμάω   1.0             +-    auto             1
448142  -6.633250 1     Q.S.     13    203      3       λαιμοῖο       λαιμάω   4.0            ++-    auto             1
467694  -6.633250 1   Theoc.     15     98      6     ἀρίστευσε     ἀριστεύω   9.0           ++++    auto             1
39945   -6.244998 1   Argon.      4    778      2       ἱππότεω      ἱππότης   3.0           +--+    auto             1
255258  -6.244998 1    Dion.     30    115      5  αὐτοκύλιστον αὐτοκύλιστος   7.0          +--+-    auto             1
354173  -6.244998 1      Od.     13    226      7      ἐναντίος     ἐναντίος   8.5           -+--    auto             1
470893  -6.244998 1   Theoc.     21     58      7      ἐπήρατον     ἐπήρατος   8.5           -+--    auto             1
162470  -6.164414 1      Il.     21    283      4       ἔναυλος      ἔναυλος   2.5            -+-    auto             1
250882  -6.164414 1    Dion.     28     82      3         φονῆα       φονεύς   4.5            -+-    auto             1
273222  -6.038601 1    Dion.     37    598      1         ταρσῷ       ταρσός   1.0             ++    auto             1
160830  -6.000000 1      Il.     21     60      6        ἀκωκῆς        ἀκωκή   6.5            -++    auto             1
435481  -6.000000 1     Q.S.      9    489      7       ἐδητύος       ἐδητύς   8.5           -+--    auto             1
191467  -5.990762 2    Dion.      4     82      6      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
222109  -5.990762 2    Dion.     15    286      4      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
1914    -5.980608 2   Phaen.      1    280      2       ταρσοῖο       ταρσός   4.0            ++-    auto             1
207841  -5.980608 2    Dion.     10    241      3       ταρσοῖο       ταρσός   4.0            ++-    auto             1
194561  -5.916080 1    Dion.      5    136      5  πολυδαίδαλον πολυδαίδαλος   8.0          --+--    auto             1
436886  -5.830952 1     Q.S.     10    145      5     ἀπείριτον    ἀπείριτος   8.5           -+--    auto             1
482365  -5.830952 1   Theog.    Th.    859      3 κεραυνωθέντος     κεραυνόω   2.5          -+++-    auto             1
98416   -5.799409 2      Il.      7    212      3     προσώπασι     πρόσωπον   6.5           -+--    auto             1
372893  -5.799409 2      Od.     18    192      5     προσώπατα     πρόσωπον   6.5           -+--    auto             1
```

Program to generate the above:

```
# src/join-expectancy corpus/*.csv expectancy.all.csv > joined.all.csv
# Rscript low-z.R joined.all.csv
COLUMNS <- c("z", "x", "work", "book_n", "line_n", "word_n", "word", "lemma", "sedes", "metrical_shape", "scanned", "num_scansions")
data <- data.frame()
for (csv_filename in commandArgs(trailingOnly=TRUE)) {
	data <- rbind(data, read.csv(csv_filename, na.strings=c(""), stringsAsFactors=FALSE))
}
options(width=200)
head(data[order(data$z), COLUMNS], 50)
```

The pair with minimum expectancy, λυαῖος/10 is so low because it appears (only in Dion.) 215 times at sedes 10.5, and once at sedes 10 (at line 20.236). Note also that the metrical shape at sedes 10 is `+++` while the shape at sedes 10.5 is `-++`.

<details>
<summary><code>grep λυαῖος joined.all.csv</code></summary>
<pre>
Dion.,7,164,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,7,288,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,9,18,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,9,112,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,9,115,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,9,198,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,86,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,126,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,144,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,211,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,248,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,320,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,399,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,10,428,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,16,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,44,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,59,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,76,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,114,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,119,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,123,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,135,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,204,8,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,11,211,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,12,109,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,12,117,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,12,153,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,13,38,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,14,5,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,14,128,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,14,170,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,14,272,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,14,291,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,15,155,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,10,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,136,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,140,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,147,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,191,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,223,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,249,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,340,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,347,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,371,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,383,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,389,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,16,395,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,50,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,104,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,131,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,174,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,239,6,λυαῖος,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,247,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,257,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,321,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,346,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,17,354,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,6,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,46,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,53,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,67,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,127,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,210,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,18,318,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,4,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,11,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,46,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,51,4,λυαίῳ,λυαῖος,10.5,-++,manual,1,215,+0.0681994339470468,+1
Dion.,19,98,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,122,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,169,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,262,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,19,333,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,22,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,30,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,33,8,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,68,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,232,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,236,5,λυαίου,λυαῖος,10,+++,auto,1,1,-14.6628782986152,-1
Dion.,20,249,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,262,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,302,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,347,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,20,387,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,12,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,86,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,125,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,129,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,174,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,21,187,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,22,6,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,22,89,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,22,92,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,22,124,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,23,36,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,23,175,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,24,172,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,74,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,109,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,167,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,169,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,194,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,220,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,299,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,320,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,25,414,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,26,35,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,26,333,9,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,27,75,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,27,257,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,27,301,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,28,38,8,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,28,83,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,28,232,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,29,123,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,29,126,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,29,167,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,29,305,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,36,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,110,6,λυαίου,λυαῖος,10.5,-++,manual,1,215,+0.0681994339470468,+1
Dion.,30,134,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,200,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,208,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,231,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,30,256,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,31,7,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,31,29,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,31,79,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,31,144,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,32,102,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,32,120,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,32,146,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,11,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,22,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,45,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,160,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,167,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,33,229,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,34,38,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,34,356,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,35,306,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,35,320,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,35,328,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,35,357,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,35,375,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,36,5,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,36,319,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,36,401,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,37,75,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,37,81,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,37,722,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,38,55,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,38,62,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,10,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,114,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,262,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,323,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,381,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,39,390,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,8,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,16,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,42,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,153,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,180,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,40,415,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,41,12,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,41,421,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,42,109,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,42,432,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,42,507,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,70,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,155,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,162,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,335,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,365,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,43,420,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,44,187,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,44,211,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,44,215,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,44,298,4,λυαίῳ,λυαῖος,10.5,-++,manual,1,215,+0.0681994339470468,+1
Dion.,45,20,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,45,54,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,45,169,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,45,194,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,45,238,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,45,263,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,46,100,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,46,162,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,46,166,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,46,171,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,3,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,268,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,464,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,480,4,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,496,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,547,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,551,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,594,7,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,620,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,47,635,8,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,24,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,71,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,75,6,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,101,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,110,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,124,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,139,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,166,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,521,6,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,539,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,577,5,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,684,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,724,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,811,5,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,944,4,λυαίου,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
Dion.,48,963,7,λυαίῳ,λυαῖος,10.5,-++,auto,1,215,+0.0681994339470468,+1
</pre>
</details>

**Comment by sasansom** [comment]
233527 -14.662878 1    Dion.     20    236      5        λυαίου       λυαῖος  10.0            +++    auto             1 
--- A word, e)nhe/a, was missing an 'eta' and entered as *e)ne/a, thus corrupting the scan. Fixed corpus/nonnusdionysiaca.

90951  -12.922848 1      Il.      5    593      4      κυδοιμὸν     κυδοιμός   4.5            -+-    auto             1 
--- A proper noun, whose other instances were incorrectly lemmatized, are now corrected on lemma.py.

472197 -10.816654 1   Theoc.     22    179      4  ὑμεναιώσουσι     ὑμεναιόω   6.0         --+++-    auto             1 
--- This is in fact the only instance of the lemma in the corpus. The other instances are incorrectly lemmatized and should be from the adjective ὑμέναιος, now corrected on lemma.py.

347746 -10.440307 1      Od.     11    419      4      τραπέζας      τράπεζα   6.5            -++    auto             1 
--- This looks to be correct and could be the most unexpected sedes for a lemma in the corpus! It is the only instance of τράπεζα in a position other than 10.5. The narrative context is also interesting. It occurs in the Nekuia during Agamemnon's description of his own murder (one of the most important paranarratives of the epic, cf. opening of book 1).

107107 -10.000000 1      Il.      9    389      4      ἀφροδίτῃ     ἀφροδίτη   6.0           --++    auto             1 
--- This is correct. Ἀφροδίτη occurs otherwise at sedes 10 expect at Od. 20.73 (see next entry below). It's noteworthy since it is spoken by Achilles, a famous tinkerer with epic language.

379474 -10.000000 1      Od.     20     73      2      ἀφροδίτη     ἀφροδίτη   2.0           --++    auto             1 
--- Cf. above entry. This instance is spoken by Penelope in prayer to Artemis and may have a structural relationship, in terms of metrical position, to the surrounding passage (cf. 'Athena' above).

165027  -9.848858 1      Il.     22     27      4        ὀπώρης        ὀπώρα   2.5            -++    auto             1 
--- Correct. Occurs within a simile for Achilles shining like a star in late summer likely focalization through the eyes of Priam (cf. ἴδεν 22.25).

450325  -8.829666 1     Q.S.     13    517      6      ἀριστέας     ἀριστεύς   8.5           -+--    auto             1 
--- Correct. Occurs within last line of character speech.

152849  -8.803408 2      Il.     18    484      4       σελήνην       σελήνη   6.5            -++    auto             1 
--- Correct. Occurs in second line of the beginning of the ekphrasis of the shield of Achilles. It bears an interesting structural (metrically) and linguistic relationship to τραπέζας (Od. 11.419) above. Cp.:

> ἠέλιόν τ' ἀκάμαντα σελήνην τε πλήθουσαν (Il. 18.484)

> ὡς ἀμφὶ κρητῆρα τραπέζας τε πληθούσας (Od. 11.419)

Perhaps τε πλήθουσα has some kind of purchase on those sedes?

414589  -8.803408 2     Q.S.      5      8      6        σελήνη       σελήνη   6.5            -++    auto             1 
--- Correct. Occurs at the beginning of a retelling of the ekphrasis of Achilles' shield (cf. entry immediately above). Cp.:

> Q.S. Posthomerica 5.6-10
> Πρῶτα μὲν εὖ ἤσκητο θεοκμήτῳ ἐπὶ ἔργῳ 
> οὐρανὸς ἠδ' αἰθήρ· γαίῃ δ' ἅμα κεῖτο θάλασσα. 
> Ἐν δ' ἄνεμοι νεφέλαι τε σελήνη τ' ἠέλιός τε 
> κεκριμέν' ἄλλυδις ἄλλα· τέτυκτο δὲ τείρεα πάντα 
> ὁππόσα δινήεντα κατ' οὐρανὸν ἀμφιφέρονται. 

> Iliad 18.483-5
> Ἐν μὲν γαῖαν ἔτευξ', ἐν δ' οὐρανόν, ἐν δὲ θάλασσαν, 
> ἠέλιόν τ' ἀκάμαντα σελήνην τε πλήθουσαν, 
> ἐν δὲ τὰ τείρεα πάντα, τά τ' οὐρανὸς ἐστεφάνωται, 

Certainly intertextual, though interesting that it reuses the same very rare sedes (cf. TAPA article). I wonder what the expectancy relationship is between the other shared words (e.g., οὐρανός).

377746  -8.774964 1      Od.     19    439      5         λόχμῃ        λόχμη   4.0             ++    auto             1 
--- Correct. All other instances (x = 77) are at sedes 11. Here, the narrator is recounting the boar hunt from which Odysseus received his scar and his name.

21483   -8.124038 1   Argon.      2    714      4        χορείῃ       χορεία   6.5            -++    auto             1 
--- This seems to be mis-lemmatized as n. χορεία (᾽dance') instead of the correct lemma, the adj. χορεῖος ('belonging to dance'), which appears to be a hapax in the corpus. The TLG has the same mistake and gives both noun and adjective lemmata for every instance of χορει-, as does our program. The problem can't be fixed in lemma.py as it stands because there are other instances of the same string, χορείῃ, that belong to the noun lemma χορεία not the adj. Not sure how to proceed on this to fix it.

353425  -7.810250 1      Od.     13    123      6       ὁδιτάων       ὁδίτης   6.5           -+++    auto             1 
--- Correct. All other instances at end of line. Interesting word, may play etymologically with Odysseus' name.

396521  -7.698889 1     Q.S.      1    228      4      ἀντίθεον     ἀντίθεος   5.0           +--+    auto             1 
--- Correct. It is a proper name, whereas the other instances (basically equally distributed across three other sedes) are adjectives I bet.

397629  -7.615773 1     Q.S.      1    391      1        χάρμης        χάρμη   1.0             ++    auto             1
--- It looks like a bunch of the other instances of χάρμης (51) have been incorrectly lemmatized as the rare word χάρμης (an antidote, s.v. TLG), though they mostly follow the same metrical pattern as the correctly lemmatized instances, so I'm doubtful it will change the z-score all that much (perhaps it will make it more extreme?). I've fixed in lemma.py.

440757  -7.549834 2     Q.S.     11    214      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
--- Correct.

482394  -7.549834 2   Theog.    Th.    864      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
--- Correct. In the simile comparing the conflagration of the earth in the Typhonomachy to metalurgy. Possibly intertextual with Q.S. 11.214 above:

> Theog. 862–7
> ἐτήκετο κασσίτερος ὣς 
> τέχνῃ ὑπ' αἰζηῶν ἐν ἐυτρήτοις χοάνοισι 
> θαλφθείς, ἠὲ σίδηρος, ὅ περ κρατερώτατός ἐστιν, 
> οὔρεος ἐν βήσσῃσι δαμαζόμενος πυρὶ κηλέῳ 
> τήκεται ἐν χθονὶ δίῃ ὑφ' Ἡφαίστου παλάμῃσιν· 
> ὣς ἄρα τήκετο γαῖα σέλαι πυρὸς αἰθομένοιο. 

> Q.S. Posthomerica 11.211–5
> ἐπὶ σφίσι δ' ἄχνυται ἀνήρ, 
> ἀμφότερον ποθέων τε πόνον τρομέων τ' ἐπὶ βουσὶ 
> μὴ δή που κατόπισθεν ἐπαΐσσοντος ἀρότρου 
> κέρσῃ νεῦρα σίδηρος ἀμείλιχος ἐν ποσὶ κύρσας· 
> ὣς Δαναοὶ φοβέοντο,

304633  -7.211103 1    Dion.     48    451      5        πορείῃ       πορεία  10.0            +++    auto             1
--- XML missing "de\". Fixed in XML.

414956  -7.141428 1     Q.S.      5     61      3        ἀπήνας        ἀπήνη   2.5            -++    auto             1
--- Correct. Occurs in the ekphrasis of the shield of Achilles; cf. σελήνη above.

274279  -7.035624 1    Dion.     37    773      6          ἐνυώ         ἐνυώ  10.0            +++    auto             1
--- XML missing 'e' in "sth/santes". Fixed in XML.

478348  -7.035624 1   Theog.    Th.    273      4          ἐνυώ         ἐνυώ   6.5            -++    auto             1
--- Correct. It is the proper name (Enyo) rather than noun.

389184  -7.028344 1      Od.     23    106      3    προσφάσθαι     πρόσφημι   3.0            +++    auto             1
--- Correct. Interesting as it occurs in Penelope's response to Telemachus (cf. TAPA on Od. book 1).

85775   -7.000000 1      Il.      4    412      2         σιωπῇ        σιωπή   2.5            -++    auto             1
--- Correct. Diomedes to Sthenelos revealing the socio-political intent (and necessity) of Agamemnon's utterance.

-6.939065 4 Hom.Hymn      4     89      3       προσέφη     πρόσφημι   4.0            --+    auto             1
--- Correct. This along with the following two would be interesting test cases for the interaction of sedes and formularity (perhaps finding the limits of lemmatized expectancy). What are the potential cross-effects of formulaically expected sedes that are also rare in terms of lemma?

61697   -6.939065 4 Hom.Hymn      4    189      3       προσέφη     πρόσφημι   4.0            --+    auto             1
--- Correct. Cf. above.

143751  -6.939065 4      Il.     16    842      4       προσέφη     πρόσφημι   4.0            --+    auto             1
--- Correct. Cf. above.

348789  -6.939065 4      Od.     11    565      4       προσέφη     πρόσφημι   4.0            --+    auto             1
--- Correct. Cf. above.

44435   -6.855655 1   Argon.      4   1455      6       ἀολλεῖς       ἀολλής  10.5            -++    auto             1
--- Correct. Interesting syntax here starting at bucolic diaeresis.

72348   -6.633250 1      Il.      1    438      3     ἑκατόμβην     ἑκατόμβη   2.0           --++    auto             1
--- Correct. Rigid word order + sedes in this passage (1.436-9).

430848  -6.633250 1     Q.S.      8    322      1         λαιμῷ       λαιμάω   1.0             +-    auto             1
--- Incorrect lemma. Corrected in lemma.py to λαιμός ('throat').

448142  -6.633250 1     Q.S.     13    203      3       λαιμοῖο       λαιμάω   4.0            ++-    auto             1
--- Incorrect lemma. Corrected in lemma.py to λαιμός ('throat').

467694  -6.633250 1   Theoc.     15     98      6     ἀρίστευσε     ἀριστεύω   9.0           ++++    auto             1
--- Correct. Odd metrical lengthening of initial α in ἀρίστευσε?

39945   -6.244998 1   Argon.      4    778      2       ἱππότεω      ἱππότης   3.0           +--+    auto             1
--- Correct. Proper noun (cf., e.g., Ἐνυώ above).

255258  -6.244998 1    Dion.     30    115      5  αὐτοκύλιστον αὐτοκύλιστος   7.0          +--+-    auto             1
--- Correct. Pretty sure this word only occurs in Dion. (and Oppian's Halieutica).

354173  -6.244998 1      Od.     13    226      7      ἐναντίος     ἐναντίος   8.5           -+--    auto             1
--- Correct. This line also violates Hermann's Bridge (according to some definitions). Interesting to have another example from Odyssey 13, cf. ὁδιτάων above.

470893  -6.244998 1   Theoc.     21     58      7      ἐπήρατον     ἐπήρατος   8.5           -+--    auto             1
--- This line in _inter cruces_ in Gow's edition, so impossible to tell what to do with it without further work.

162470  -6.164414 1      Il.     21    283      4       ἔναυλος      ἔναυλος   2.5            -+-    auto             1
--- Correct. Spoken in a simile by Achilles. Check Ready for this?

250882  -6.164414 1    Dion.     28     82      3         φονῆα       φονεύς   4.5            -+-    auto             1
--- Correct. Interesting phonic hemistychic parallelism here: Δεξιόχου δὲ φονῆα καλέσσατο θυιάδι φωνῇ. Also I like the palindrome of the line number 28.82. Coincidence? Also interesting spacial semantics in the initial name, Δεξιόχου ('right'). I wonder if Nonnus was into palindromes...

273222  -6.038601 1    Dion.     37    598      1         ταρσῷ       ταρσός   1.0             ++    auto             1
--- Correct. Seems to be on account of anadiplosis: ταρσῷ ταρσὸν ἔρειδε παρὰ σφυρὸν ἄκρον ἑλίξας.

160830  -6.000000 1      Il.     21     60      6        ἀκωκῆς        ἀκωκή   6.5            -++    auto             1
--- Correct. Gnarly lines spoken by Achilles: ἀλλ' ἄγε δὴ καὶ δουρὸς ἀκωκῆς ἡμετέροιο / γεύσεται. Cf. Il. 21 in ἔναυλος above.

435481  -6.000000 1     Q.S.      9    489      7       ἐδητύος       ἐδητύς   8.5           -+--    auto             1
--- Correct. Seems to be a tinkering with an otherwise very formulaic line: Ἀλλ' ὅτε δὴ κορέσαντο ποτοῦ καὶ ἐδητύος ἐσθλῆς. Not sure why.

191467  -5.990762 2    Dion.      4     82      6      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
--- Correct. Proper name.

222109  -5.990762 2    Dion.     15    286      4      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
--- Correct. Proper name.

1914    -5.980608 2   Phaen.      1    280      2       ταρσοῖο       ταρσός   4.0            ++-    auto             1
--- Correct. Κηφείης ταρσοῖο τὰ δεξιὰ πείρατα τείνων. 

207841  -5.980608 2    Dion.     10    241      3       ταρσοῖο       ταρσός   4.0            ++-    auto             1
--- Correct. Doubtful that it's intertextual with Aratus (cf. above). Seems to be structured internally in the line by repetition of the lemma: δόχμιον ἐκ ταρσοῖο μετήλυδα ταρσὸν ἀμείβων.

194561  -5.916080 1    Dion.      5    136      5  πολυδαίδαλον πολυδαίδαλος   8.0          --+--    auto             1
--- Correct. Interesting internal structure of the lines here by 'poly' and color/material (5.135-7):

> πολυφράδμων δ' Ἀφροδίτη
> χρύσεον ὅρμον ἔχοντα λίθων πολυδαίδαλον αἴγλην 
> λευκὸν ἐρευθιόωντι συνήρμοσεν αὐχένι κούρης, 

436886  -5.830952 1     Q.S.     10    145      5     ἀπείριτον    ἀπείριτος   8.5           -+--    auto             1
--- Correct. Μαιάνδρῳ κελάδοντα ῥόον καὶ ἀπείριτον οἶδμα.

482365  -5.830952 1   Theog.    Th.    859      3 κεραυνωθέντος     κεραυνόω   2.5          -+++-    auto             1
--- Correct, but other words incorrectly lemmatized, now fixed in lemma.py.
    ("κεραυνῶν", "κεραυνός"),
    ("κεραυνοί", "κεραυνός"),

98416   -5.799409 2      Il.      7    212      3     προσώπασι     πρόσωπον   6.5           -+--    auto             1
--- Correct. Interesting, several unexpected sedes+lemma in this group occur near words for "smiling" (see Odyssey examples above): μειδιόων βλοσυροῖσι προσώπασι· νέρθε δὲ ποσσὶν.

372893  -5.799409 2      Od.     18    192      5     προσώπατα     πρόσωπον   6.5           -+--    auto             1
--- Correct. Perhaps some metrical structural reasons for this in passage.

**Comment by whoopsedesy** [comment]
> 90951 -12.922848 1 Il. 5 593 4 κυδοιμὸν κυδοιμός 4.5 -+- auto 1
> --- A proper noun, whose other instances were incorrectly lemmatized, are now corrected on lemma.py.

The fix for this didn't work. I'm still showing −12.92 as being the minimum lemma. There is an entry for κυδοιμὸς in lemma.py, but it needs one for κυδοιμὸν.

Here's the new list of least 50 (as of 06b0a781da2002c0cf35a32448566a5c3224e74c), if you want to quickly look it over and see if there are any others that stuck around but should not have. I marked the 4 entries that were not in the previous list with `+`.

```
                  z x     work book_n line_n word_n          word        lemma sedes metrical_shape scanned num_scansions
  90951  -12.922848 1      Il.      5    593      4      κυδοιμὸν     κυδοιμός   4.5            -+-    auto             1
  347747 -10.440307 1      Od.     11    419      4      τραπέζας      τράπεζα   6.5            -++    auto             1
  107107 -10.000000 1      Il.      9    389      4      ἀφροδίτῃ     ἀφροδίτη   6.0           --++    auto             1
  379475 -10.000000 1      Od.     20     73      2      ἀφροδίτη     ἀφροδίτη   2.0           --++    auto             1
  478349 -10.000000 1   Theog.    Th.    273      4          ἐνυώ         ἐνυώ   6.5            -++    auto             1
  165027  -9.848858 1      Il.     22     27      4        ὀπώρης        ὀπώρα   2.5            -++    auto             1
  450326  -8.829666 1     Q.S.     13    517      6      ἀριστέας     ἀριστεύς   8.5           -+--    auto             1
  152849  -8.803408 2      Il.     18    484      4       σελήνην       σελήνη   6.5            -++    auto             1
  414590  -8.803408 2     Q.S.      5      8      6        σελήνη       σελήνη   6.5            -++    auto             1
  377747  -8.774964 1      Od.     19    439      5         λόχμῃ        λόχμη   4.0             ++    auto             1
  21483   -8.124038 1   Argon.      2    714      4        χορείῃ       χορεία   6.5            -++    auto             1
  353426  -7.810250 1      Od.     13    123      6       ὁδιτάων       ὁδίτης   6.5           -+++    auto             1
  396522  -7.698889 1     Q.S.      1    228      4      ἀντίθεον     ἀντίθεος   5.0           +--+    auto             1
  397630  -7.615773 1     Q.S.      1    391      1        χάρμης        χάρμη   1.0             ++    auto             1
  440758  -7.549834 2     Q.S.     11    214      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
  482395  -7.549834 2   Theog.    Th.    864      3       σίδηρος      σίδηρος   4.5            -+-    auto             1
  414957  -7.141428 1     Q.S.      5     61      3        ἀπήνας        ἀπήνη   2.5            -++    auto             1
  389185  -7.028344 1      Od.     23    106      3    προσφάσθαι     πρόσφημι   3.0            +++    auto             1
  85775   -7.000000 1      Il.      4    412      2         σιωπῇ        σιωπή   2.5            -++    auto             1
  61007   -6.939065 4 Hom.Hymn      4     89      3       προσέφη     πρόσφημι   4.0            --+    auto             1
  61697   -6.939065 4 Hom.Hymn      4    189      3       προσέφη     πρόσφημι   4.0            --+    auto             1
  143751  -6.939065 4      Il.     16    842      4       προσέφη     πρόσφημι   4.0            --+    auto             1
  348790  -6.939065 4      Od.     11    565      4       προσέφη     πρόσφημι   4.0            --+    auto             1
  44435   -6.855655 1   Argon.      4   1455      6       ἀολλεῖς       ἀολλής  10.5            -++    auto             1
  72348   -6.633250 1      Il.      1    438      3     ἑκατόμβην     ἑκατόμβη   2.0           --++    auto             1
  430849  -6.633250 1     Q.S.      8    322      1         λαιμῷ       λαιμάω   1.0             +-    auto             1
  448143  -6.633250 1     Q.S.     13    203      3       λαιμοῖο       λαιμάω   4.0            ++-    auto             1
  467695  -6.633250 1   Theoc.     15     98      6     ἀρίστευσε     ἀριστεύω   9.0           ++++    auto             1
  39945   -6.244998 1   Argon.      4    778      2       ἱππότεω      ἱππότης   3.0           +--+    auto             1
  255258  -6.244998 1    Dion.     30    115      5  αὐτοκύλιστον αὐτοκύλιστος   7.0          +--+-    auto             1
  354174  -6.244998 1      Od.     13    226      7      ἐναντίος     ἐναντίος   8.5           -+--    auto             1
  470894  -6.244998 1   Theoc.     21     58      7      ἐπήρατον     ἐπήρατος   8.5           -+--    auto             1
  162470  -6.164414 1      Il.     21    283      4       ἔναυλος      ἔναυλος   2.5            -+-    auto             1
  250882  -6.164414 1    Dion.     28     82      3         φονῆα       φονεύς   4.5            -+-    auto             1
  273222  -6.038601 1    Dion.     37    598      1         ταρσῷ       ταρσός   1.0             ++    auto             1
  160830  -6.000000 1      Il.     21     60      6        ἀκωκῆς        ἀκωκή   6.5            -++    auto             1
  435482  -6.000000 1     Q.S.      9    489      7       ἐδητύος       ἐδητύς   8.5           -+--    auto             1
  191467  -5.990762 2    Dion.      4     82      6      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
  222109  -5.990762 2    Dion.     15    286      4      κυθέρεια     κυθέρεια   8.0           --+-    auto             1
  1914    -5.980608 2   Phaen.      1    280      2       ταρσοῖο       ταρσός   4.0            ++-    auto             1
  207841  -5.980608 2    Dion.     10    241      3       ταρσοῖο       ταρσός   4.0            ++-    auto             1
  194561  -5.916080 1    Dion.      5    136      5  πολυδαίδαλον πολυδαίδαλος   8.0          --+--    auto             1
  436887  -5.830952 1     Q.S.     10    145      5     ἀπείριτον    ἀπείριτος   8.5           -+--    auto             1
  482366  -5.830952 1   Theog.    Th.    859      3 κεραυνωθέντος     κεραυνόω   2.5          -+++-    auto             1
  98416   -5.799409 2      Il.      7    212      3     προσώπασι     πρόσωπον   6.5           -+--    auto             1
  372894  -5.799409 2      Od.     18    192      5     προσώπατα     πρόσωπον   6.5           -+--    auto             1
+ 18519   -5.787918 2   Argon.      2    267      5        ἄελλαι        ἄελλα   4.5            -+-    auto             1
+ 438984  -5.787918 2     Q.S.     10    440      3         ἄελλα        ἄελλα   4.5            -+-    auto             1
+ 152322  -5.738769 4      Il.     18    414      4       πρόσωπα     πρόσωπον   4.5            -+-    auto             1
+ 413254  -5.738769 4     Q.S.      4    403      5       πρόσωπα     πρόσωπον   4.5            -+-    auto             1
```

**Comment by whoopsedesy** [comment]
> 21483 -8.124038 1 Argon. 2 714 4 χορείῃ χορεία 6.5 -++ auto 1
> --- This seems to be mis-lemmatized as n. χορεία (᾽dance') instead of the correct lemma, the adj. χορεῖος ('belonging to dance'), which appears to be a hapax in the corpus. The TLG has the same mistake and gives both noun and adjective lemmata for every instance of χορει-, as does our program. The problem can't be fixed in lemma.py as it stands because there are other instances of the same string, χορείῃ, that belong to the noun lemma χορεία not the adj. Not sure how to proceed on this to fix it.

CLTK doesn't currently do it, but this is perhaps something that a lemmatizer that considers surrounding context could handle. This is what #33 is about. (But #33 won't have any effect until CLTK supports a Greek lemmatizer that takes context into account (or we do our own simple one).)

**Comment by whoopsedesy** [comment]
> The fix for this didn't work. I'm still showing −12.92 as being the minimum lemma. There is an entry for κυδοιμὸς in lemma.py, but it needs one for κυδοιμὸν.

This is taken care of by d3282b0da8e76482dc5c681c2fd37f50d4136c22.

The updated *z*-score frequency histogram:

![z-dist all](https://user-images.githubusercontent.com/53617134/109080415-685fae00-76f8-11eb-85bd-e0510983b526.png)
